# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ec7d4a588275c5bf5e0ccbe5e464f529d34a7cca1c905db52400f8b53811fb66d438e324eea39a7a121f578dc7d17af1e4c0fe5b1c226299a840cfd5c70578b

test:
  secret_key_base: 2148721cc28bc154f26ae64db5929796bc2d8aef7b3411ce2634a65d0fb0d3ff1782839ea63aeec47b946b0520c2874bd1893cec54c080f30aa45447be96141e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
